package Entity;
// Generated 21/10/2018 17:24:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Claselicencia generated by hbm2java
 */
public class Claselicencia  implements java.io.Serializable {


     private int idclaselicencia;
     private String claselicencia;
     private Set licencias = new HashSet(0);

    public Claselicencia() {
    }

	
    public Claselicencia(int idclaselicencia, String claselicencia) {
        this.idclaselicencia = idclaselicencia;
        this.claselicencia = claselicencia;
    }
    public Claselicencia(int idclaselicencia, String claselicencia, Set licencias) {
       this.idclaselicencia = idclaselicencia;
       this.claselicencia = claselicencia;
       this.licencias = licencias;
    }
   
    public int getIdclaselicencia() {
        return this.idclaselicencia;
    }
    
    public void setIdclaselicencia(int idclaselicencia) {
        this.idclaselicencia = idclaselicencia;
    }
    public String getClaselicencia() {
        return this.claselicencia;
    }
    
    public void setClaselicencia(String claselicencia) {
        this.claselicencia = claselicencia;
    }
    public Set getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set licencias) {
        this.licencias = licencias;
    }




}


