package Entity;
// Generated 21/10/2018 17:24:18 by Hibernate Tools 4.3.1



/**
 * Costolicencia generated by hbm2java
 */
public class Costolicencia  implements java.io.Serializable {


     private CostolicenciaId id;
     private Integer precio;

    public Costolicencia() {
    }

	
    public Costolicencia(CostolicenciaId id) {
        this.id = id;
    }
    public Costolicencia(CostolicenciaId id, Integer precio) {
       this.id = id;
       this.precio = precio;
    }
   
    public CostolicenciaId getId() {
        return this.id;
    }
    
    public void setId(CostolicenciaId id) {
        this.id = id;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }




}


