package Entity;
// Generated 21/10/2018 17:24:18 by Hibernate Tools 4.3.1



/**
 * CostolicenciaId generated by hbm2java
 */
public class CostolicenciaId  implements java.io.Serializable {


     private short claselicencia;
     private int vigencia;

    public CostolicenciaId() {
    }

    public CostolicenciaId(short claselicencia, int vigencia) {
       this.claselicencia = claselicencia;
       this.vigencia = vigencia;
    }
   
    public short getClaselicencia() {
        return this.claselicencia;
    }
    
    public void setClaselicencia(short claselicencia) {
        this.claselicencia = claselicencia;
    }
    public int getVigencia() {
        return this.vigencia;
    }
    
    public void setVigencia(int vigencia) {
        this.vigencia = vigencia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CostolicenciaId) ) return false;
		 CostolicenciaId castOther = ( CostolicenciaId ) other; 
         
		 return (this.getClaselicencia()==castOther.getClaselicencia())
 && (this.getVigencia()==castOther.getVigencia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClaselicencia();
         result = 37 * result + this.getVigencia();
         return result;
   }   


}


