package Entity;
// Generated 21/10/2018 17:24:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gruposanguineo generated by hbm2java
 */
public class Gruposanguineo  implements java.io.Serializable {


     private int idgruposanguineo;
     private String gruposanguineo;
     private String factor;
     private Set titulars = new HashSet(0);

    public Gruposanguineo() {
    }

	
    public Gruposanguineo(int idgruposanguineo, String gruposanguineo) {
        this.idgruposanguineo = idgruposanguineo;
        this.gruposanguineo = gruposanguineo;
    }
    public Gruposanguineo(int idgruposanguineo, String gruposanguineo, String factor, Set titulars) {
       this.idgruposanguineo = idgruposanguineo;
       this.gruposanguineo = gruposanguineo;
       this.factor = factor;
       this.titulars = titulars;
    }
   
    public int getIdgruposanguineo() {
        return this.idgruposanguineo;
    }
    
    public void setIdgruposanguineo(int idgruposanguineo) {
        this.idgruposanguineo = idgruposanguineo;
    }
    public String getGruposanguineo() {
        return this.gruposanguineo;
    }
    
    public void setGruposanguineo(String gruposanguineo) {
        this.gruposanguineo = gruposanguineo;
    }
    public String getFactor() {
        return this.factor;
    }
    
    public void setFactor(String factor) {
        this.factor = factor;
    }
    public Set getTitulars() {
        return this.titulars;
    }
    
    public void setTitulars(Set titulars) {
        this.titulars = titulars;
    }




}


