package Entity;
// Generated 21/10/2018 17:24:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sexo generated by hbm2java
 */
public class Sexo  implements java.io.Serializable {


     private int idsexo;
     private String sexo;
     private Set titulars = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Sexo() {
    }

	
    public Sexo(int idsexo, String sexo) {
        this.idsexo = idsexo;
        this.sexo = sexo;
    }
    public Sexo(int idsexo, String sexo, Set titulars, Set usuarios) {
       this.idsexo = idsexo;
       this.sexo = sexo;
       this.titulars = titulars;
       this.usuarios = usuarios;
    }
   
    public int getIdsexo() {
        return this.idsexo;
    }
    
    public void setIdsexo(int idsexo) {
        this.idsexo = idsexo;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Set getTitulars() {
        return this.titulars;
    }
    
    public void setTitulars(Set titulars) {
        this.titulars = titulars;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


