package Entity;
// Generated 21/10/2018 17:24:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipodocumento generated by hbm2java
 */
public class Tipodocumento  implements java.io.Serializable {


     private int idtipodocumento;
     private String tipodocumento;
     private Set titulars = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Tipodocumento() {
    }

	
    public Tipodocumento(int idtipodocumento, String tipodocumento) {
        this.idtipodocumento = idtipodocumento;
        this.tipodocumento = tipodocumento;
    }
    public Tipodocumento(int idtipodocumento, String tipodocumento, Set titulars, Set usuarios) {
       this.idtipodocumento = idtipodocumento;
       this.tipodocumento = tipodocumento;
       this.titulars = titulars;
       this.usuarios = usuarios;
    }
   
    public int getIdtipodocumento() {
        return this.idtipodocumento;
    }
    
    public void setIdtipodocumento(int idtipodocumento) {
        this.idtipodocumento = idtipodocumento;
    }
    public String getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(String tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public Set getTitulars() {
        return this.titulars;
    }
    
    public void setTitulars(Set titulars) {
        this.titulars = titulars;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


