package Entity;
// Generated 21/10/2018 17:24:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Titular generated by hbm2java
 */
public class Titular  implements java.io.Serializable {


     private int idtitular;
     private Gruposanguineo gruposanguineo;
     private Nacionalidad nacionalidad;
     private Sexo sexo;
     private Tipodocumento tipodocumento;
     private String nombre;
     private String apellido;
     private String numerodocumento;
     private Date fechanacimiento;
     private String direccion;
     private short donante;
     private short idempleadogestor;
     private Date fechagestion;
     private Set<Licencia> licencias = new HashSet<Licencia>();

    public Titular() {
    }

	
    public Titular(int idtitular, Gruposanguineo gruposanguineo, Nacionalidad nacionalidad, Sexo sexo, Tipodocumento tipodocumento, String nombre, String apellido, String numerodocumento, Date fechanacimiento, String direccion, short donante, short idempleadogestor, Date fechagestion) {
        this.idtitular = idtitular;
        this.gruposanguineo = gruposanguineo;
        this.nacionalidad = nacionalidad;
        this.sexo = sexo;
        this.tipodocumento = tipodocumento;
        this.nombre = nombre;
        this.apellido = apellido;
        this.numerodocumento = numerodocumento;
        this.fechanacimiento = fechanacimiento;
        this.direccion = direccion;
        this.donante = donante;
        this.idempleadogestor = idempleadogestor;
        this.fechagestion = fechagestion;
    }
    public Titular(int idtitular, Gruposanguineo gruposanguineo, Nacionalidad nacionalidad, Sexo sexo, Tipodocumento tipodocumento, String nombre, String apellido, String numerodocumento, Date fechanacimiento, String direccion, short donante, short idempleadogestor, Date fechagestion, Set licencias) {
       this.idtitular = idtitular;
       this.gruposanguineo = gruposanguineo;
       this.nacionalidad = nacionalidad;
       this.sexo = sexo;
       this.tipodocumento = tipodocumento;
       this.nombre = nombre;
       this.apellido = apellido;
       this.numerodocumento = numerodocumento;
       this.fechanacimiento = fechanacimiento;
       this.direccion = direccion;
       this.donante = donante;
       this.idempleadogestor = idempleadogestor;
       this.fechagestion = fechagestion;
       this.licencias = licencias;
    }
   
    public int getIdtitular() {
        return this.idtitular;
    }
    
    public void setIdtitular(int idtitular) {
        this.idtitular = idtitular;
    }
    public Gruposanguineo getGruposanguineo() {
        return this.gruposanguineo;
    }
    
    public void setGruposanguineo(Gruposanguineo gruposanguineo) {
        this.gruposanguineo = gruposanguineo;
    }
    public Nacionalidad getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(Nacionalidad nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Sexo getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }
    public Tipodocumento getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(Tipodocumento tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNumerodocumento() {
        return this.numerodocumento;
    }
    
    public void setNumerodocumento(String numerodocumento) {
        this.numerodocumento = numerodocumento;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public short getDonante() {
        return this.donante;
    }
    
    public void setDonante(short donante) {
        this.donante = donante;
    }
    public short getIdempleadogestor() {
        return this.idempleadogestor;
    }
    
    public void setIdempleadogestor(short idempleadogestor) {
        this.idempleadogestor = idempleadogestor;
    }
    public Date getFechagestion() {
        return this.fechagestion;
    }
    
    public void setFechagestion(Date fechagestion) {
        this.fechagestion = fechagestion;
    }
    public Set<Licencia> getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set licencias) {
        this.licencias = licencias;
    }




}


