package Entity;
// Generated 21/10/2018 17:24:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Sexo sexo;
     private Tipodocumento tipodocumento;
     private String nombreusuario;
     private String contrasena;
     private String nombre;
     private String apellido;
     private Date fechanacimiento;
     private String numerodocumento;
     private String direccion;
     private String numerotelefono;
     private String email;
     private boolean permisosuperusuario;
     private short idempleadogestor;
     private Date fechagestion;
     private Set licencias = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, Sexo sexo, Tipodocumento tipodocumento, String nombreusuario, String contrasena, String nombre, String apellido, Date fechanacimiento, String numerodocumento, String direccion, String email, boolean permisosuperusuario, short idempleadogestor, Date fechagestion) {
        this.idusuario = idusuario;
        this.sexo = sexo;
        this.tipodocumento = tipodocumento;
        this.nombreusuario = nombreusuario;
        this.contrasena = contrasena;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechanacimiento = fechanacimiento;
        this.numerodocumento = numerodocumento;
        this.direccion = direccion;
        this.email = email;
        this.permisosuperusuario = permisosuperusuario;
        this.idempleadogestor = idempleadogestor;
        this.fechagestion = fechagestion;
    }
    public Usuario(int idusuario, Sexo sexo, Tipodocumento tipodocumento, String nombreusuario, String contrasena, String nombre, String apellido, Date fechanacimiento, String numerodocumento, String direccion, String numerotelefono, String email, boolean permisosuperusuario, short idempleadogestor, Date fechagestion, Set licencias) {
       this.idusuario = idusuario;
       this.sexo = sexo;
       this.tipodocumento = tipodocumento;
       this.nombreusuario = nombreusuario;
       this.contrasena = contrasena;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechanacimiento = fechanacimiento;
       this.numerodocumento = numerodocumento;
       this.direccion = direccion;
       this.numerotelefono = numerotelefono;
       this.email = email;
       this.permisosuperusuario = permisosuperusuario;
       this.idempleadogestor = idempleadogestor;
       this.fechagestion = fechagestion;
       this.licencias = licencias;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Sexo getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }
    public Tipodocumento getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(Tipodocumento tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getNumerodocumento() {
        return this.numerodocumento;
    }
    
    public void setNumerodocumento(String numerodocumento) {
        this.numerodocumento = numerodocumento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNumerotelefono() {
        return this.numerotelefono;
    }
    
    public void setNumerotelefono(String numerotelefono) {
        this.numerotelefono = numerotelefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isPermisosuperusuario() {
        return this.permisosuperusuario;
    }
    
    public void setPermisosuperusuario(boolean permisosuperusuario) {
        this.permisosuperusuario = permisosuperusuario;
    }
    public short getIdempleadogestor() {
        return this.idempleadogestor;
    }
    
    public void setIdempleadogestor(short idempleadogestor) {
        this.idempleadogestor = idempleadogestor;
    }
    public Date getFechagestion() {
        return this.fechagestion;
    }
    
    public void setFechagestion(Date fechagestion) {
        this.fechagestion = fechagestion;
    }
    public Set getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set licencias) {
        this.licencias = licencias;
    }




}


